Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2023-04, with the labels that each got.

#261 Upgrade to v0.36 of the C++ Hedera protobufs
  .github/workflows/zxc-build-library.yaml
  HederaApi.cmake
  sdk/main/include/AccountCreateTransaction.h
  sdk/main/include/AccountId.h
  sdk/main/include/EvmAddress.h
  sdk/main/include/Status.h
  sdk/main/src/AccountCreateTransaction.cc
  sdk/main/src/AccountId.cc
  sdk/main/src/Status.cc
  sdk/tests/unit/AccountCreateTransactionTest.cc
  sdk/tests/unit/AccountIdTest.cc
  sdk/tests/unit/NodeAddressTest.cc
  sdk/tests/unit/TransactionTest.cc
Labels: Feature Enhancement

#262 `Transaction::fromBytes` not properly deserializing
  sdk/main/src/Transaction.cc
Labels: Bug

#266 Upgrade to v0.36 of C++ Hedera protobufs
  HederaApi.cmake
Labels: Feature Enhancement

#268 Implement `ContractCallQuery`
  sdk/main/CMakeLists.txt
  sdk/main/include/ContractCallQuery.h
  sdk/main/include/ContractFunctionResult.h
  sdk/main/include/ContractId.h
  sdk/main/include/ContractLogInfo.h
  sdk/main/include/TransactionRecord.h
  sdk/main/include/TransferTransaction.h
  sdk/main/src/ContractCallQuery.cc
  sdk/main/src/ContractFunctionResult.cc
  sdk/main/src/ContractId.cc
  sdk/main/src/ContractLogInfo.cc
  sdk/main/src/Executable.cc
  sdk/main/src/TransactionRecord.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/ContractCallQueryTest.cc
  sdk/tests/unit/ContractFunctionResultTest.cc
  sdk/tests/unit/ContractIdTest.cc
  sdk/tests/unit/ContractLogInfoTest.cc
  sdk/tests/unit/TransactionRecordTest.cc
Labels: New Feature

#272 Implement `ContractDeleteTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/ContractCreateTransaction.h
  sdk/main/include/ContractDeleteTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/ContractDeleteTransaction.cc
  sdk/main/src/Executable.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/ContractDeleteTransactionTest.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#277 Hash mismatch when pulling v0.36 C++ Hedera protobufs
  HederaApi.cmake
Labels: Bug

#278 Implement `ContractFunctionParameters` and `ContractFunctionSelector`
  sdk/main/CMakeLists.txt
  sdk/main/include/ContractFunctionParameters.h
  sdk/main/include/ContractFunctionSelector.h
  sdk/main/include/impl/Utilities.h
  sdk/main/include/impl/openssl_utils/OpenSSLUtils.h
  sdk/main/src/ContractFunctionParameters.cc
  sdk/main/src/ContractFunctionResult.cc
  sdk/main/src/ContractFunctionSelector.cc
  sdk/main/src/ECDSAsecp256k1PrivateKey.cc
  sdk/main/src/ECDSAsecp256k1PublicKey.cc
  sdk/main/src/ED25519PrivateKey.cc
  sdk/main/src/ED25519PublicKey.cc
  sdk/main/src/MnemonicBIP39.cc
  sdk/main/src/PrivateKey.cc
  sdk/main/src/impl/HexConverter.cc
  sdk/main/src/impl/OpenSSLUtils.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/ContractFunctionParametersTest.cc
  sdk/tests/unit/ContractFunctionResultTest.cc
  sdk/tests/unit/ContractFunctionSelectorTest.cc
Labels: New Feature

#267 Failing steps in the PR checks workflow (PR)
  .github/workflows/zxc-build-library.yaml
Labels: Blocker

#282 Fix failure of test `LedgerIdTest.FromBadStrings` (PR)
  sdk/tests/unit/LedgerIdTest.cc
Labels: Bug

#283 Add CreateSimpleContractExample
  config/hello_world.json
  sdk/examples/CMakeLists.txt
  sdk/examples/CreateSimpleContractExample.cc
  sdk/main/include/ContractCallQuery.h
  sdk/main/include/ContractCreateTransaction.h
  sdk/main/include/ContractFunctionParameters.h
  sdk/main/include/ContractFunctionSelector.h
  sdk/main/include/ContractId.h
  sdk/main/include/Defaults.h
  sdk/main/include/FileCreateTransaction.h
  sdk/main/include/TransactionReceipt.h
  sdk/main/src/ContractCallQuery.cc
  sdk/main/src/ContractCreateTransaction.cc
  sdk/main/src/ContractFunctionParameters.cc
  sdk/main/src/ContractFunctionSelector.cc
  sdk/main/src/ContractId.cc
  sdk/main/src/FileCreateTransaction.cc
  sdk/main/src/TransactionReceipt.cc
  sdk/tests/unit/ContractFunctionParametersTest.cc
  sdk/tests/unit/ContractFunctionSelectorTest.cc
  sdk/tests/unit/ContractIdTest.cc
  sdk/tests/unit/TransactionReceiptTest.cc
Labels: New Feature

#226 Step-by-step guide to distribute a new release (PR)
  CONTRIBUTING.md
  README.md
Labels: Improvement
