Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2023-10, with the labels that each got.

#511 Some examples aren't working properly
  sdk/examples/AccountCreateWithHtsExample.cc
  sdk/examples/ExemptCustomFeesExample.cc
  sdk/examples/TransferCryptoExample.cc
  sdk/main/include/Client.h
  sdk/main/include/TokenMintTransaction.h
  sdk/main/include/impl/BaseNetwork.h
  sdk/main/include/impl/BaseNode.h
  sdk/main/include/impl/MirrorNode.h
  sdk/main/include/impl/Network.h
  sdk/main/include/impl/Node.h
  sdk/main/src/Client.cc
  sdk/main/src/Executable.cc
  sdk/main/src/Query.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/BaseNetwork.cc
  sdk/main/src/impl/BaseNode.cc
  sdk/main/src/impl/BaseNodeAddress.cc
  sdk/main/src/impl/MirrorNetwork.cc
  sdk/main/src/impl/MirrorNode.cc
  sdk/main/src/impl/Network.cc
  sdk/main/src/impl/Node.cc
Labels: Bug

#512 Add `TransactionId` argument to `TransactionReceipt::fromProtobuf()`
  sdk/main/include/TransactionReceipt.h
  sdk/main/src/TransactionReceipt.cc
  sdk/main/src/TransactionReceiptQuery.cc
  sdk/tests/integration/TransactionReceiptQueryIntegrationTest.cc
Labels: Bug

#513 Install address book and config files
  sdk/main/CMakeLists.txt
Labels: Bug, Release

#397 Integration test for node selection (PR)
  .github/workflows/zxc-build-library.yaml
  sdk/main/include/Client.h
  sdk/main/src/Client.cc
  sdk/tests/integration/ClientIntegrationTest.cc
  sdk/tests/unit/ClientTest.cc
Labels: Improvement

#520 Add `ConsensusPubSubWithSubmitKeyExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/ConsensusPubSubWithSubmitKeyExample.cc
Labels: New Feature

#526 Add `CreateAccountThresholdKeyExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/CreateAccountThresholdKeyExample.cc
Labels: New Feature

#532 Add `GenerateKeyExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/GenerateKeyExample.cc
Labels: New Feature

#529 Add `CreateFileExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/CreateFileExample.cc
  sdk/main/include/FileCreateTransaction.h
  sdk/main/src/FileCreateTransaction.cc
  sdk/tests/integration/FileDeleteTransactionIntegrationTests.cc
Labels: New Feature

#536 Add `GetExchangeRatesExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/GetExchangeRatesExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/ExchangeRate.h
  sdk/main/include/ExchangeRates.h
  sdk/main/include/TransactionReceipt.h
  sdk/main/src/ExchangeRate.cc
  sdk/main/src/ExchangeRates.cc
  sdk/main/src/TransactionReceipt.cc
  sdk/tests/integration/TransactionReceiptIntegrationTest.cc
  sdk/tests/integration/TransactionRecordIntegrationTest.cc
  sdk/tests/unit/ExchangeRateTest.cc
  sdk/tests/unit/TransactionReceiptTest.cc
Labels: New Feature

#539 Add `MultiAppTransferExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/MultiAppTransferExample.cc
Labels: New Feature

#530 Add `CreateTopicExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/CreateTopicExample.cc
Labels: New Feature

#542 Fix windows build
  sdk/main/src/impl/EntityIdHelper.cc
Labels: Bug

#548 Project examples/ runs resulting in errors (PR)
  .gitignore
  sdk/main/src/impl/Network.cc
Labels: Bug

#544 Add `PrngExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/PrngExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/PrngTransaction.h
  sdk/main/include/TransactionRecord.h
  sdk/main/include/TransactionType.h
  sdk/main/include/WrappedTransaction.h
  sdk/main/include/impl/Node.h
  sdk/main/src/Executable.cc
  sdk/main/src/PrngTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/TransactionRecord.cc
  sdk/main/src/WrappedTransaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/PrngTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/PrngTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#549 Add `MultiSigOfflineExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/MultiSigOfflineExample.cc
  sdk/main/include/PrivateKey.h
  sdk/main/include/Transaction.h
  sdk/main/src/PrivateKey.cc
  sdk/main/src/Transaction.cc
Labels: New Feature

#550 Add `SignTransactionExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/SignTransactionExample.cc
  sdk/main/src/Transaction.cc
Labels: New Feature

#562 Add `TransferUsingEvmAddressExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/TransferUsingEvmAddressExample.cc
  sdk/main/include/TransferTransaction.h
  sdk/main/src/TransferTransaction.cc
Labels: New Feature

#558 Add `StakingWithUpdateExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/StakingWithUpdateExample.cc
  sdk/main/include/AccountUpdateTransaction.h
  sdk/main/src/AccountUpdateTransaction.cc
  sdk/tests/unit/AccountUpdateTransactionTest.cc
Labels: New Feature

#555 Add HTTP Client for querying MirrorNode (PR)
  CMakeLists.txt
  sdk/main/CMakeLists.txt
  sdk/main/include/impl/HttpClient.h
  sdk/main/src/impl/HttpClient.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/HttpClientIntegrationTests.cc
  vcpkg.json
Labels: New Feature

#556 Add `SolidityPrecompileExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/ContractHelper.h
  sdk/examples/SolidityPrecompileExample.cc
  sdk/examples/precompile-example/ExpiryHelper.sol
  sdk/examples/precompile-example/FeeHelper.sol
  sdk/examples/precompile-example/HederaResponseCodes.sol
  sdk/examples/precompile-example/HederaTokenService.sol
  sdk/examples/precompile-example/IHederaTokenService.sol
  sdk/examples/precompile-example/IPrngSystemContract.sol
  sdk/examples/precompile-example/KeyHelper.sol
  sdk/examples/precompile-example/PrecompileExample.json
  sdk/examples/precompile-example/PrecompileExample.sol
  sdk/examples/precompile-example/PrngSystemContract.sol
  sdk/examples/precompile-example/ZeroTokenOperations.json
  sdk/examples/precompile-example/ZeroTokenOperations.sol
Labels: New Feature

#564 Add `ZeroTokenOperationsExample`
  sdk/examples/CMakeLists.txt
  sdk/examples/ZeroTokenOperationsExample.cc
Labels: New Feature

#565 Add missing APIs for `CustomFee`s and derived classes
  sdk/main/include/CustomFee.h
  sdk/main/src/CustomFee.cc
  sdk/tests/unit/CustomFixedFeeTest.cc
  sdk/tests/unit/CustomFractionalFeeTest.cc
  sdk/tests/unit/CustomRoyaltyFeeTest.cc
Labels: Improvement

#567 Fix `AccountId` `evmAddress` field not being displayed correctly in `toSolidityAddress()`
  sdk/main/include/AccountId.h
  sdk/main/src/AccountId.cc
  sdk/main/src/impl/Network.cc
Labels: Bug

#573 Fix Windows build
  sdk/main/src/AccountId.cc
  sdk/tests/integration/HttpClientIntegrationTests.cc
Labels: Bug
