Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2023-07, with the labels that each got.

#403 Implement `TokenBurnTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenBurnTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/include/TransactionReceipt.h
  sdk/main/src/Executable.cc
  sdk/main/src/TokenBurnTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenBurnTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenBurnTransactionUnitTests.cc
  sdk/tests/unit/TransactionReceiptTest.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#404 Implement `TokenDissociateTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenDissociateTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/TokenDissociateTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenDissociateTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenDissociateTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#402 Implement `TokenInfoQuery`
  sdk/main/CMakeLists.txt
  sdk/main/include/AccountInfo.h
  sdk/main/include/TokenInfo.h
  sdk/main/include/TokenInfoQuery.h
  sdk/main/include/TransferTransaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/Query.cc
  sdk/main/src/TokenInfo.cc
  sdk/main/src/TokenInfoQuery.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenInfoQueryIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenInfoQueryUnitTests.cc
  sdk/tests/unit/TokenInfoUnitTests.cc
Labels: New Feature

#405 Implement `TokenFeeScheduleUpdateTransaction`
  sdk/examples/CMakeLists.txt
  sdk/examples/CustomFeesExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/CustomFixedFee.h
  sdk/main/include/TokenFeeScheduleUpdateTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/CustomFixedFee.cc
  sdk/main/src/Executable.cc
  sdk/main/src/TokenFeeScheduleUpdateTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenCreateTransactionIntegrationTests.cc
  sdk/tests/integration/TokenFeeScheduleUpdateTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/CustomFixedFeeTest.cc
  sdk/tests/unit/TokenFeeScheduleUpdateTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#406 Implement `TokenGrantKycTransaction`
  sdk/examples/TransferTokensExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenGrantKycTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/TokenGrantKycTransaction.cc
  sdk/main/src/TokenWipeTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/TransactionReceipt.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenGrantKycTransactionIntegrationTests.cc
  sdk/tests/integration/TokenWipeTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenGrantKycTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#407 Implement `TokenRevokeKycTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenRevokeKycTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/TokenRevokeKycTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenRevokeKycTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenRevokeKycTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#409 Implement `TokenUnpauseTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenUnpauseTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/TokenUnpauseTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenUnpauseTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenUnpauseTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#410 Implement `TokenFreezeTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenFreezeTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/TokenFreezeTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenFreezeTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenFreezeTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#411 Implement `TokenUnfreezeTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenUnfreezeTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/TokenUnfreezeTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenUnfreezeTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenUnfreezeTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#433 Upgrade to v0.40 of the C++ Hedera protobufs (PR)
  HederaApi.cmake
Labels: Feature Enhancement

#436 Fix CI/CD build due to `ca-certificates` installation issue
  .github/workflows/zxc-build-library.yaml
Labels: Bug

#414 Implement `TokenNftInfoQuery`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenNftInfo.h
  sdk/main/include/TokenNftInfoQuery.h
  sdk/main/include/TransferTransaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/Query.cc
  sdk/main/src/TokenNftInfo.cc
  sdk/main/src/TokenNftInfoQuery.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenNftInfoQueryIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenNftInfoQueryUnitTests.cc
Labels: New Feature

#416 Update `TokenAllowance`
  sdk/main/include/TokenAllowance.h
  sdk/main/src/TokenAllowance.cc
  sdk/tests/unit/AccountAllowanceApproveTransactionTest.cc
  sdk/tests/unit/TokenAllowanceTest.cc
Labels: Improvement

#420 Update `TokenTransfer`
  sdk/main/include/TokenTransfer.h
  sdk/main/src/TokenTransfer.cc
  sdk/main/src/TransactionRecord.cc
  sdk/main/src/TransferTransaction.cc
  sdk/tests/unit/TokenTransferTest.cc
  sdk/tests/unit/TransactionRecordTest.cc
Labels: Feature Enhancement

#424 Add GRPC keepalive options
  sdk/main/src/impl/Node.cc
Labels: Bug, Improvement

#418 `Update TokenNftAllowance`
  sdk/main/CMakeLists.txt
  sdk/main/include/AccountAllowanceDeleteTransaction.h
  sdk/main/include/TokenNftAllowance.h
  sdk/main/include/TokenNftRemoveAllowance.h
  sdk/main/src/AccountAllowanceApproveTransaction.cc
  sdk/main/src/AccountAllowanceDeleteTransaction.cc
  sdk/main/src/TokenNftAllowance.cc
  sdk/main/src/TokenNftRemoveAllowance.cc
  sdk/tests/unit/AccountAllowanceApproveTransactionTest.cc
  sdk/tests/unit/AccountAllowanceDeleteTransactionTest.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenNftAllowanceTest.cc
  sdk/tests/unit/TokenNftRemoveAllowanceTest.cc
Labels: Feature Enhancement

#425 Implement `TopicCreateTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TopicCreateTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/include/impl/Node.h
  sdk/main/src/Executable.cc
  sdk/main/src/TopicCreateTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TopicCreateTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TopicCreateTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#434 Implement `TopicId`
  sdk/main/CMakeLists.txt
  sdk/main/include/TopicId.h
  sdk/main/include/TransactionReceipt.h
  sdk/main/src/TopicId.cc
  sdk/main/src/TransactionReceipt.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TopicIdUnitTests.cc
  sdk/tests/unit/TransactionReceiptTest.cc
Labels: New Feature

#438 Implement `TopicDeleteTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TopicDeleteTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/TopicDeleteTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TopicCreateTransactionIntegrationTests.cc
  sdk/tests/integration/TopicDeleteTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TopicDeleteTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature
