Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2023-06, with the labels that each got.

#334 Add `ChunkedTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/ChunkedTransaction.h
  sdk/main/include/Executable.h
  sdk/main/src/ChunkedTransaction.cc
Labels: New Feature

#336 Add `FileUpdateTransaction` to `Transaction::fromBytes()` and add unit tests
  sdk/main/include/Transaction.h
  sdk/main/src/Transaction.cc
  sdk/tests/unit/TransactionTest.cc
Labels: Escape

#337 Iimplement `FileAppendTransaction`
  sdk/examples/CMakeLists.txt
  sdk/examples/FileAppendChunkedExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/ChunkedTransaction.h
  sdk/main/include/FileAppendTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/ChunkedTransaction.cc
  sdk/main/src/Executable.cc
  sdk/main/src/FileAppendTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/FileAppendTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/ChunkedTransactionTest.cc
  sdk/tests/unit/FileAppendTransactionTest.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#339 Integration tests - common logic to setup the local node - Part 1 (PR)
  sdk/tests/integration/AccountAllowanceApproveTransactionIntegrationTests.cc
  sdk/tests/integration/AccountBalanceQueryIntegrationTest.cc
  sdk/tests/integration/AccountCreateTransactionIntegrationTest.cc
  sdk/tests/integration/AccountDeleteTransactionIntegrationTest.cc
  sdk/tests/integration/AccountInfoQueryIntegrationTests.cc
  sdk/tests/integration/AccountRecordsQueryIntegrationTests.cc
  sdk/tests/integration/AccountUpdateTransactionIntegrationTest.cc
  sdk/tests/integration/BaseIntegrationTest.cc
  sdk/tests/integration/BaseIntegrationTest.h
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/ContractBytecodeQueryIntegrationTests.cc
  sdk/tests/integration/ContractCallQueryIntegrationTests.cc
  sdk/tests/integration/ContractCreateTransactionIntegrationTests.cc
  sdk/tests/integration/ContractDeleteTransactionIntegrationTests.cc
  sdk/tests/integration/ContractExecuteTransactionIntegrationTests.cc
  sdk/tests/integration/ContractInfoQueryIntegrationTests.cc
  sdk/tests/integration/ContractUpdateTransactionIntegrationTests.cc
Labels: Improvement

#345 Implement `DelegateContractId`
  sdk/main/CMakeLists.txt
  sdk/main/include/DelegateContractId.h
  sdk/main/src/DelegateContractId.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/DelegateContractIdTest.cc
Labels: New Feature

#347 Implement `EthereumFlow`
  sdk/main/CMakeLists.txt
  sdk/main/include/EthereumFlow.h
  sdk/main/include/EthereumTransaction.h
  sdk/main/include/FileAppendTransaction.h
  sdk/main/src/EthereumFlow.cc
  sdk/main/src/EthereumTransaction.cc
  sdk/main/src/FileAppendTransaction.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/EthereumFlowTest.cc
  sdk/tests/unit/EthereumTransactionTest.cc
Labels: New Feature

#351 Implement `TokenType`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenType.h
  sdk/main/src/TokenType.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenTypeTest.cc
Labels: New Feature

#353 Implement `TokenSupplyType`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenSupplyType.h
  sdk/main/src/TokenSupplyType.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenSupplyTypeTest.cc
Labels: New Feature

#341 Integration tests - common logic to setup the local node - Part 2 (PR)
  sdk/tests/integration/BaseIntegrationTest.cc
  sdk/tests/integration/BaseIntegrationTest.h
  sdk/tests/integration/ContractCreateFlowIntegrationTest.cc
  sdk/tests/integration/FileAppendTransactionIntegrationTests.cc
  sdk/tests/integration/FileContentsQueryIntegrationTest.cc
  sdk/tests/integration/FileCreateTransactionIntegrationTests.cc
  sdk/tests/integration/FileDeleteTransactionIntegrationTests.cc
  sdk/tests/integration/FileInfoQueryIntegrationTests.cc
  sdk/tests/integration/FileUpdateTransactionIntegrationTests.cc
  sdk/tests/integration/TransactionIntegrationTest.cc
  sdk/tests/integration/TransactionReceiptIntegrationTest.cc
  sdk/tests/integration/TransactionReceiptQueryIntegrationTest.cc
  sdk/tests/integration/TransactionRecordIntegrationTest.cc
  sdk/tests/integration/TransactionRecordQueryIntegrationTest.cc
  sdk/tests/integration/TransferTransactionIntegrationTest.cc
  sdk/tests/unit/ClientTest.cc
Labels: Improvement

#375 Upgrade to `v0.39` of the C++ Hedera protobufs
  HederaApi.cmake
Labels: Feature Enhancement

#372 Improve build time of OpenSSL on Linux and MacOS
  BuildOpenSSL.cmake
Labels: Improvement

#362 Add `FeeAssessmentMethod`
  sdk/main/include/FeeAssessmentMethod.h
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/FeeAssessmentMethodTest.cc
Labels: New Feature

#359 Implement `CustomFixedFee`
  sdk/main/CMakeLists.txt
  sdk/main/include/CustomFee.h
  sdk/main/include/CustomFeeBase.h
  sdk/main/include/CustomFixedFee.h
  sdk/main/src/CustomFee.cc
  sdk/main/src/CustomFeeBase.cc
  sdk/main/src/CustomFixedFee.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/CustomFixedFeeTest.cc
Labels: New Feature

#391 Implement `TokenCreateTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenCreateTransaction.h
  sdk/main/include/TokenSupplyType.h
  sdk/main/include/TokenType.h
  sdk/main/include/TransactionReceipt.h
  sdk/main/include/impl/Node.h
  sdk/main/src/CustomFee.cc
  sdk/main/src/CustomFeeBase.cc
  sdk/main/src/CustomFixedFee.cc
  sdk/main/src/CustomRoyaltyFee.cc
  sdk/main/src/Executable.cc
  sdk/main/src/TokenCreateTransaction.cc
  sdk/main/src/TokenSupplyType.cc
  sdk/main/src/TokenType.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/TransactionReceipt.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenCreateTransactionIntegrationTests.cc
  sdk/tests/integration/TransactionReceiptIntegrationTest.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenCreateTransactionTest.cc
  sdk/tests/unit/TransactionReceiptTest.cc
Labels: New Feature

#392 Implement `TokenDeleteTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenDeleteTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/TokenDeleteTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenCreateTransactionIntegrationTests.cc
  sdk/tests/integration/TokenDeleteTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenDeleteTransactionTest.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#394 Implement `AssessedCustomFees`
  sdk/examples/CMakeLists.txt
  sdk/examples/ExemptCustomFeesExample.cc
  sdk/examples/TransferCryptoExample.cc
  sdk/examples/TransferTokensExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/AssessedCustomFee.h
  sdk/main/include/TransactionRecord.h
  sdk/main/src/AssessedCustomFee.cc
  sdk/main/src/TokenCreateTransaction.cc
  sdk/main/src/TransactionRecord.cc
  sdk/tests/integration/TransactionRecordIntegrationTest.cc
  sdk/tests/integration/TransactionRecordQueryIntegrationTest.cc
  sdk/tests/integration/TransferTransactionIntegrationTest.cc
  sdk/tests/unit/AssessedCustomFeesTest.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TransactionRecordTest.cc
Labels: Improvement, New Feature

#395 Implement `TokenAssociateTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenAssociateTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/TokenAssociateTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenAssociateTransactionIntegrationTests.cc
  sdk/tests/integration/TransactionReceiptIntegrationTest.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenAssociateTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#396 Implement `TokenAssociation`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenAssociation.h
  sdk/main/include/TransactionRecord.h
  sdk/main/src/TokenAssociation.cc
  sdk/main/src/TransactionRecord.cc
  sdk/tests/integration/TokenAssociateTransactionIntegrationTests.cc
  sdk/tests/integration/TransactionReceiptIntegrationTest.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenAssociationUnitTests.cc
  sdk/tests/unit/TransactionRecordTest.cc
Labels: New Feature

#399 Implement `TokenUpdateTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TokenUpdateTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/TokenUpdateTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TokenUpdateTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TokenUpdateTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature
