Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2023-11, with the labels that each got.

#574 Full implementation for `Query`
  sdk/main/include/Executable.h
  sdk/main/include/Query.h
  sdk/main/src/Query.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/QueryIntegrationTests.cc
Labels: Feature Enhancement

#575 Full implementation for `TransactionReceipt`
  sdk/main/include/Status.h
  sdk/main/include/TransactionReceipt.h
  sdk/main/src/Status.cc
  sdk/main/src/TransactionReceipt.cc
  sdk/tests/integration/TransactionReceiptIntegrationTest.cc
  sdk/tests/integration/TransactionRecordIntegrationTest.cc
  sdk/tests/unit/TransactionReceiptTest.cc
Labels: Feature Enhancement

#577 Full implementation for `ChunkedTransaction`
  sdk/main/include/ChunkedTransaction.h
  sdk/main/include/Executable.h
  sdk/main/src/ChunkedTransaction.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/ChunkedTransactionIntegrationTests.cc
  sdk/tests/integration/ExecutableIntegrationTests.cc
Labels: Feature Enhancement

#578 Full implementation for `TransactionId`
  sdk/examples/ScheduleExample.cc
  sdk/main/include/TransactionId.h
  sdk/main/src/Transaction.cc
  sdk/main/src/TransactionId.cc
  sdk/main/src/TransactionReceiptQuery.cc
  sdk/main/src/TransactionRecordQuery.cc
  sdk/tests/unit/ScheduleInfoUnitTests.cc
  sdk/tests/unit/TransactionIdTest.cc
  sdk/tests/unit/TransactionRecordTest.cc
Labels: Feature Enhancement

#579 Full implementation for `TransactionRecord`
  sdk/main/include/TransactionRecord.h
  sdk/main/src/TransactionRecord.cc
  sdk/tests/unit/TransactionRecordTest.cc
Labels: Feature Enhancement

#581 Full implementation for `TransactionResponse`
  sdk/examples/AutoCreateAccountTransferTransactionExample.cc
  sdk/examples/ScheduleExample.cc
  sdk/examples/TransferUsingEvmAddressExample.cc
  sdk/main/include/ChunkedTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/include/TransactionResponse.h
  sdk/main/src/ChunkedTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/TransactionResponse.cc
  sdk/tests/integration/TransactionReceiptIntegrationTest.cc
  sdk/tests/integration/TransactionReceiptQueryIntegrationTest.cc
  sdk/tests/integration/TransactionRecordQueryIntegrationTest.cc
  sdk/tests/unit/TransactionResponseTest.cc
Labels: Feature Enhancement

#589 Upgrade to `v0.42.0` of Hedera C++ Protobuf API (PR)
  HederaApi.cmake
Labels: Improvement

#592 Full implementation of `Client`
  sdk/examples/ConsensusPubSubChunkedExample.cc
  sdk/examples/ConsensusPubSubExample.cc
  sdk/examples/ConsensusPubSubWithSubmitKeyExample.cc
  sdk/examples/CreateSimpleContractExample.cc
  sdk/examples/CreateStatefulContractExample.cc
  sdk/main/include/Client.h
  sdk/main/include/Defaults.h
  sdk/main/include/TopicMessageQuery.h
  sdk/main/src/AccountId.cc
  sdk/main/src/AddressBookQuery.cc
  sdk/main/src/Client.cc
  sdk/main/src/Executable.cc
  sdk/main/src/Query.cc
  sdk/main/src/TopicMessageQuery.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/EntityIdHelper.cc
  sdk/tests/integration/TopicMessageQueryIntegrationTests.cc
Labels: Feature Enhancement

#602 Add stream overloads for key classes
  sdk/main/include/PrivateKey.h
  sdk/main/include/PublicKey.h
  sdk/main/src/PrivateKey.cc
  sdk/main/src/PublicKey.cc
Labels: New Feature

#608 Upgrade to v0.43.0 of Hedera C++ Protobuf API
  HederaApi.cmake
Labels: Improvement

#586 Add missing fee classes
  sdk/main/CMakeLists.txt
  sdk/main/include/FeeComponents.h
  sdk/main/include/FeeData.h
  sdk/main/include/FeeDataType.h
  sdk/main/include/FeeSchedule.h
  sdk/main/include/FeeSchedules.h
  sdk/main/include/RequestType.h
  sdk/main/include/TransactionFeeSchedule.h
  sdk/main/include/impl/TimestampConverter.h
  sdk/main/src/FeeComponents.cc
  sdk/main/src/FeeData.cc
  sdk/main/src/FeeDataType.cc
  sdk/main/src/FeeSchedule.cc
  sdk/main/src/FeeSchedules.cc
  sdk/main/src/RequestType.cc
  sdk/main/src/TransactionFeeSchedule.cc
  sdk/main/src/TransactionId.cc
  sdk/main/src/impl/TimestampConverter.cc
Labels: New Feature

#609 Implement `Hbar` (PR)
  sdk/main/CMakeLists.txt
  sdk/main/include/Hbar.h
  sdk/main/src/Hbar.cc
Labels: Improvement

#610 Implement `.env` file for examples
  .env.sample
  .gitignore
  sdk/examples/AccountAliasExample.cc
  sdk/examples/AccountAllowanceExample.cc
  sdk/examples/AccountCreateWithHtsExample.cc
  sdk/examples/AutoCreateAccountTransferTransactionExample.cc
  sdk/examples/CMakeLists.txt
  sdk/examples/ConsensusPubSubChunkedExample.cc
  sdk/examples/ConsensusPubSubExample.cc
  sdk/examples/ConsensusPubSubWithSubmitKeyExample.cc
  sdk/examples/ContractNoncesExample.cc
  sdk/examples/CreateAccountExample.cc
  sdk/examples/CreateAccountThresholdKeyExample.cc
  sdk/examples/CreateFileExample.cc
  sdk/examples/CreateSimpleContractExample.cc
  sdk/examples/CreateStatefulContractExample.cc
  sdk/examples/CreateTopicExample.cc
  sdk/examples/CustomFeesExample.cc
  sdk/examples/DeleteAccountExample.cc
  sdk/examples/DeleteFileExample.cc
  sdk/examples/ExemptCustomFeesExample.cc
  sdk/examples/FileAppendChunkedExample.cc
  sdk/examples/GetAccountInfoExample.cc
  sdk/examples/GetExchangeRatesExample.cc
  sdk/examples/GetFileContentsExample.cc
  sdk/examples/MultiAppTransferExample.cc
  sdk/examples/MultiSigOfflineExample.cc
  sdk/examples/NftAddRemoveAllowancesExample.cc
  sdk/examples/PrngExample.cc
  sdk/examples/ScheduleExample.cc
  sdk/examples/ScheduleIdenticalTransactionExample.cc
  sdk/examples/ScheduleMultiSigTransactionExample.cc
  sdk/examples/ScheduleTransactionMultiSigThresholdExample.cc
  sdk/examples/ScheduleTransferExample.cc
  sdk/examples/SignTransactionExample.cc
  sdk/examples/SolidityPrecompileExample.cc
  sdk/examples/StakingExample.cc
  sdk/examples/StakingWithUpdateExample.cc
  sdk/examples/TopicWithAdminKeyExample.cc
  sdk/examples/TransferCryptoExample.cc
  sdk/examples/TransferTokensExample.cc
  sdk/examples/TransferUsingEvmAddressExample.cc
  sdk/examples/UpdateAccountPublicKeyExample.cc
  sdk/examples/ValidateChecksumExample.cc
  sdk/examples/ZeroTokenOperationsExample.cc
Labels: New Feature

#612 Upgrade to `v0.44.0` of Hedera C++ Protobuf API
  HederaApi.cmake
Labels: Improvement

#607 Added EC Private Keys compatibility to improve OpenSSL Key import compatibility.
  sdk/main/CMakeLists.txt
  sdk/main/include/impl/ASN1ECKey.h
  sdk/main/include/impl/ASN1ECPrivateKey.h
  sdk/main/include/impl/ASN1Object.h
  sdk/main/include/impl/HexConverter.h
  sdk/main/src/ECDSAsecp256k1PrivateKey.cc
  sdk/main/src/impl/ASN1ECPrivateKey.cc
  sdk/main/src/impl/HexConverter.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/unit/ECDSAsecp256k1PrivateKeyTest.cc
Labels: Feature Enhancement

#614 Fix Windows build
  sdk/tests/unit/ECDSAsecp256k1PrivateKeyTest.cc
Labels: Bug

#620 Fix OpenSSL public ECDSA keys import compatibility
  sdk/main/CMakeLists.txt
  sdk/main/include/impl/ASN1ECKey.h
  sdk/main/include/impl/ASN1ECPrivateKey.h
  sdk/main/include/impl/ASN1ECPublicKey.h
  sdk/main/include/impl/ASN1Object.h
  sdk/main/src/ECDSAsecp256k1PrivateKey.cc
  sdk/main/src/ECDSAsecp256k1PublicKey.cc
  sdk/main/src/impl/ASN1ECKey.cc
  sdk/main/src/impl/ASN1ECPrivateKey.cc
  sdk/main/src/impl/ASN1ECPublicKey.cc
  sdk/tests/unit/ECDSAsecp256k1PrivateKeyUnitTests.cc
  sdk/tests/unit/ECDSAsecp256k1PublicKeyUnitTests.cc
Labels: Feature Enhancement
