Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2023-08, with the labels that each got.

#442 Implement `TopicUpdateTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/TopicUpdateTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/TopicUpdateTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TopicUpdateTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/TopicUpdateTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#447 Implement `TopicMessageSubmitTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/ChunkedTransaction.h
  sdk/main/include/TopicMessageSubmitTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/ChunkedTransaction.cc
  sdk/main/src/Executable.cc
  sdk/main/src/TopicMessageSubmitTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TopicMessageSubmitTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/ChunkedTransactionTest.cc
  sdk/tests/unit/TopicMessageSubmitTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#456 Implement `ScheduleId`
  sdk/main/CMakeLists.txt
  sdk/main/include/ScheduleId.h
  sdk/main/include/TransactionReceipt.h
  sdk/main/include/TransactionRecord.h
  sdk/main/src/ScheduleId.cc
  sdk/main/src/TransactionReceipt.cc
  sdk/main/src/TransactionRecord.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/ScheduleIdUnitTests.cc
  sdk/tests/unit/TransactionReceiptTest.cc
  sdk/tests/unit/TransactionRecordTest.cc
Labels: New Feature

#458 Implement `ScheduleDeleteTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/ScheduleDeleteTransaction.h
  sdk/main/include/TransactionType.h
  sdk/main/include/WrappedTransaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/ScheduleCreateTransaction.cc
  sdk/main/src/ScheduleDeleteTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/WrappedTransaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/ScheduleDeleteTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/ScheduleDeleteTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#465 Implement `ScheduleSignTransaction`
  sdk/examples/CMakeLists.txt
  sdk/examples/ScheduleExample.cc
  sdk/examples/ScheduleIdenticalTransactionExample.cc
  sdk/examples/ScheduleMultiSigTransactionExample.cc
  sdk/examples/ScheduleTransactionMultiSigThresholdExample.cc
  sdk/examples/ScheduleTransferExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/KeyList.h
  sdk/main/include/ScheduleSignTransaction.h
  sdk/main/include/TransactionType.h
  sdk/main/include/WrappedTransaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/KeyList.cc
  sdk/main/src/ScheduleSignTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/WrappedTransaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/ScheduleSignTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/ScheduleSignTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#467 Upgrade to `v0.41.0` of Hedera C++ Protobuf API (PR)
  HederaApi.cmake
  sdk/main/src/NftId.cc
  sdk/tests/unit/NftIdTest.cc
Labels: Feature Enhancement

#469 Fix Windows builds
  sdk/examples/ScheduleIdenticalTransactionExample.cc
  sdk/examples/ScheduleTransactionMultiSigThresholdExample.cc
Labels: New Feature

#453 Add HIP-729 Contract Nonces to ContractFunctionResult (PR)
  sdk/main/CMakeLists.txt
  sdk/main/include/ContractFunctionResult.h
  sdk/main/include/ContractNonceInfo.h
  sdk/main/src/ContractFunctionResult.cc
  sdk/main/src/ContractNonceInfo.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/ContractFunctionResultTest.cc
  sdk/tests/unit/ContractNonceInfoUnitTests.cc
Labels: New Feature

#472 Integration test for `ContractNonceInfo` (PR)
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/ContractNonceInfoIntegrationTest.cc
Labels: Improvement

#477 Implement `SystemDeleteTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/SystemDeleteTransaction.h
  sdk/main/include/TransactionType.h
  sdk/main/include/WrappedTransaction.h
  sdk/main/include/impl/TimestampConverter.h
  sdk/main/src/Executable.cc
  sdk/main/src/SystemDeleteTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/WrappedTransaction.cc
  sdk/main/src/impl/Node.cc
  sdk/main/src/impl/TimestampConverter.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/SystemDeleteTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/SystemDeleteTransactionUnitTests.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#491 Example for `ContractNonceInfo` (PR)
  sdk/examples/CMakeLists.txt
  sdk/examples/ContractNoncesExample.cc
Labels: Feature Enhancement

#487 Add `AccountAliasExample`
  sdk/examples/AccountAliasExample.cc
  sdk/examples/CMakeLists.txt
  sdk/main/include/ECDSAsecp256k1PublicKey.h
  sdk/main/include/ED25519PublicKey.h
  sdk/main/include/PublicKey.h
  sdk/main/src/AccountId.cc
  sdk/main/src/AccountInfo.cc
  sdk/main/src/ECDSAsecp256k1PublicKey.cc
  sdk/main/src/ED25519PublicKey.cc
  sdk/main/src/PublicKey.cc
  sdk/tests/unit/AccountIdTest.cc
  sdk/tests/unit/AccountInfoTest.cc
Labels: New Feature
