Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2023-02, with the labels that each got.

#188 Include features introduced in Hedera protobufs since `v0.30`
  sdk/examples/CreateAccountExample.cc
  sdk/examples/GetAccountBalanceExample.cc
  sdk/examples/TransferCryptoExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/AccountCreateTransaction.h
  sdk/main/include/AccountId.h
  sdk/main/include/EvmAddress.h
  sdk/main/include/PublicKey.h
  sdk/main/include/Status.h
  sdk/main/include/TransactionRecord.h
  sdk/main/src/AccountCreateTransaction.cc
  sdk/main/src/AccountId.cc
  sdk/main/src/ECDSAPublicKey.cc
  sdk/main/src/ED25519PublicKey.cc
  sdk/main/src/EvmAddress.cc
  sdk/main/src/PublicKey.cc
  sdk/main/src/TransactionRecord.cc
  sdk/main/src/impl/HexConverter.cc
  sdk/tests/AccountCreateTransactionTest.cc
  sdk/tests/AccountIdTest.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/EvmAddressTest.cc
  sdk/tests/TransactionIdTest.cc
  sdk/tests/TransactionRecordTest.cc
Labels: New Feature

#189 Rename all ECDSA key instances to `ECDSAsecp256k1`
  sdk/examples/GeneratePrivateKeyFromMnemonic.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/ECDSAPrivateKey.h
  sdk/main/include/ECDSAsecp256k1PrivateKey.h
  sdk/main/include/ECDSAsecp256k1PublicKey.h
  sdk/main/src/ECDSAsecp256k1PrivateKey.cc
  sdk/main/src/ECDSAsecp256k1PublicKey.cc
  sdk/main/src/PublicKey.cc
  sdk/tests/AccountIdTest.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/ECDSAsecp256k1PrivateKeyTest.cc
  sdk/tests/ECDSAsecp256k1PublicKeyTest.cc
Labels: Improvement

#190 Test and fix memory leaks
  sdk/main/src/ECDSAsecp256k1PrivateKey.cc
  sdk/main/src/ECDSAsecp256k1PublicKey.cc
  sdk/main/src/ED25519PrivateKey.cc
  sdk/main/src/ED25519PublicKey.cc
  sdk/tests/CMakeLists.txt
Labels: Improvement

#191 Use `std::unique_ptr` to manage OpenSSL memory allocations when able
  sdk/main/include/ECDSAsecp256k1PrivateKey.h
  sdk/main/include/ECDSAsecp256k1PublicKey.h
  sdk/main/include/ED25519PrivateKey.h
  sdk/main/include/ED25519PublicKey.h
  sdk/main/include/impl/OpenSSLObjectWrapper.h
  sdk/main/src/ECDSAsecp256k1PrivateKey.cc
  sdk/main/src/ECDSAsecp256k1PublicKey.cc
  sdk/main/src/ED25519PrivateKey.cc
  sdk/main/src/ED25519PublicKey.cc
Labels: Improvement

#195 Conform to SDK standard for generating `PrivateKey`s from `Mnemonic`
  sdk/examples/GeneratePrivateKeyFromMnemonic.cc
  sdk/main/include/ECDSAsecp256k1PrivateKey.h
  sdk/main/include/ED25519PrivateKey.h
  sdk/main/include/MnemonicBIP39.h
  sdk/main/src/ECDSAsecp256k1PrivateKey.cc
  sdk/main/src/ED25519PrivateKey.cc
  sdk/main/src/MnemonicBIP39.cc
  sdk/tests/ED25519PrivateKeyTest.cc
Labels: Improvement

#196 Add missed wrapper objects
  sdk/main/CMakeLists.txt
  sdk/main/include/ECDSAsecp256k1PrivateKey.h
  sdk/main/include/ECDSAsecp256k1PublicKey.h
  sdk/main/include/impl/BigNumber.h
  sdk/main/include/impl/OpenSSLObjectWrapper.h
  sdk/main/src/ECDSAsecp256k1PrivateKey.cc
  sdk/main/src/ECDSAsecp256k1PublicKey.cc
  sdk/main/src/MnemonicBIP39.cc
  sdk/main/src/impl/BigNumber.cc
  sdk/main/src/impl/OpenSSLHasher.cc
  sdk/main/src/impl/OpenSSLObjectWrapper.cc
Labels: Improvement

#198 Create more descriptive exceptions
  sdk/main/include/AccountCreateTransaction.h
  sdk/main/include/Client.h
  sdk/main/include/ECDSAsecp256k1PrivateKey.h
  sdk/main/include/ECDSAsecp256k1PublicKey.h
  sdk/main/include/ED25519PrivateKey.h
  sdk/main/include/ED25519PublicKey.h
  sdk/main/include/EvmAddress.h
  sdk/main/include/Executable.h
  sdk/main/include/Mnemonic.h
  sdk/main/include/MnemonicBIP39.h
  sdk/main/include/Transaction.h
  sdk/main/include/TransactionResponse.h
  sdk/main/include/TransferTransaction.h
  sdk/main/include/exceptions/BadKeyException.h
  sdk/main/include/exceptions/BadMnemonicException.h
  sdk/main/include/exceptions/MaxAttemptsExceededException.h
  sdk/main/include/exceptions/OpenSSLException.h
  sdk/main/include/exceptions/PrecheckStatusException.h
  sdk/main/include/exceptions/UninitializedException.h
  sdk/main/include/impl/HexConverter.h
  sdk/main/include/impl/Network.h
  sdk/main/include/impl/Node.h
  sdk/main/include/impl/OpenSSLHasher.h
  sdk/main/include/impl/OpenSSLRandom.h
  sdk/main/src/AccountCreateTransaction.cc
  sdk/main/src/Client.cc
  sdk/main/src/ECDSAsecp256k1PrivateKey.cc
  sdk/main/src/ECDSAsecp256k1PublicKey.cc
  sdk/main/src/ED25519PrivateKey.cc
  sdk/main/src/ED25519PublicKey.cc
  sdk/main/src/Executable.cc
  sdk/main/src/Mnemonic.cc
  sdk/main/src/MnemonicBIP39.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/HexConverter.cc
  sdk/main/src/impl/Node.cc
  sdk/main/src/impl/OpenSSLHasher.cc
  sdk/main/src/impl/OpenSSLObjectWrapper.cc
  sdk/main/src/impl/OpenSSLRandom.cc
  sdk/tests/AccountCreateTransactionTest.cc
  sdk/tests/ClientTest.cc
  sdk/tests/ECDSAsecp256k1PrivateKeyTest.cc
  sdk/tests/ECDSAsecp256k1PublicKeyTest.cc
  sdk/tests/ED25519PrivateKeyTest.cc
  sdk/tests/ED25519PublicKeyTest.cc
  sdk/tests/MnemonicBIP39Test.cc
Labels: Improvement

#200 Add additional cryptography test vectors
  sdk/main/include/MnemonicBIP39.h
  sdk/main/src/MnemonicBIP39.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/ECDSAsecp256k1PrivateKeyTest.cc
  sdk/tests/ED25519PrivateKeyTest.cc
  sdk/tests/vectors/BIP39TestVectors.cc
  sdk/tests/vectors/Hedera12WordMnemonicBIP39TestVectors.cc
  sdk/tests/vectors/Hedera24WordMnemonicBIP39TestVectors.cc
  sdk/tests/vectors/SLIP10TestVectors.cc
Labels: Improvement

#203 Install OpenSSL libraries
  BuildOpenSSL.cmake
Labels: Bug, Release

#208 Add nlohmann_json framework for JSON data
  CMakeLists.txt
  config/local_node.json
  sdk/tests/CMakeLists.txt
  sdk/tests/JSONTest.cc
  vcpkg.json
Labels: Blocker, Improvement

#206 Add token support to `TransferTransaction`
  sdk/examples/CMakeLists.txt
  sdk/examples/TransferCryptoExample.cc
  sdk/examples/TransferTokensExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/Hbar.h
  sdk/main/include/HbarTransfer.h
  sdk/main/include/NftId.h
  sdk/main/include/TokenId.h
  sdk/main/include/TokenNftTransfer.h
  sdk/main/include/TokenTransfer.h
  sdk/main/include/TransactionRecord.h
  sdk/main/include/TransferTransaction.h
  sdk/main/src/HbarTransfer.cc
  sdk/main/src/NftId.cc
  sdk/main/src/TokenId.cc
  sdk/main/src/TokenNftTransfer.cc
  sdk/main/src/TokenTransfer.cc
  sdk/main/src/TransactionRecord.cc
  sdk/main/src/TransactionRecordQuery.cc
  sdk/main/src/TransferTransaction.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/HbarTest.cc
  sdk/tests/NftIdTest.cc
  sdk/tests/TokenIdTest.cc
  sdk/tests/TokenNftTransferTest.cc
  sdk/tests/TokenTransferTest.cc
  sdk/tests/TransactionRecordTest.cc
  sdk/tests/TransferTest.cc
  sdk/tests/TransferTransactionTest.cc
Labels: New Feature

#210 Create `OpenSSLUtils` namespace and move all OpenSSL utility classes/functions into it
  sdk/examples/TransferTokensExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/ECDSAsecp256k1PrivateKey.h
  sdk/main/include/ECDSAsecp256k1PublicKey.h
  sdk/main/include/ED25519PrivateKey.h
  sdk/main/include/ED25519PublicKey.h
  sdk/main/include/impl/OpenSSLHasher.h
  sdk/main/include/impl/OpenSSLRandom.h
  sdk/main/include/impl/OpenSSLUtils.h
  sdk/main/src/ECDSAsecp256k1PrivateKey.cc
  sdk/main/src/ECDSAsecp256k1PublicKey.cc
  sdk/main/src/ED25519PrivateKey.cc
  sdk/main/src/ED25519PublicKey.cc
  sdk/main/src/Mnemonic.cc
  sdk/main/src/MnemonicBIP39.cc
  sdk/main/src/impl/HederaCertificateVerifier.cc
  sdk/main/src/impl/HexConverter.cc
  sdk/main/src/impl/OpenSSLHasher.cc
  sdk/main/src/impl/OpenSSLObjectWrapper.cc
  sdk/main/src/impl/OpenSSLRandom.cc
  sdk/main/src/impl/OpenSSLUtils.cc
Labels: Improvement

#209 Implement `Transaction::fromBytes()`
  sdk/main/include/AccountCreateTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/include/TransferTransaction.h
  sdk/main/src/AccountCreateTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/TransferTransaction.cc
  sdk/tests/AccountCreateTransactionTest.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/TransactionTest.cc
  sdk/tests/TransferTransactionTest.cc
Labels: New Feature
