Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2023-03, with the labels that each got.

#221 Remove clone() for `Executable` and all derived classes
  sdk/main/include/AccountBalanceQuery.h
  sdk/main/include/AccountCreateTransaction.h
  sdk/main/include/Executable.h
  sdk/main/include/TransactionReceiptQuery.h
  sdk/main/include/TransactionRecordQuery.h
  sdk/main/include/TransferTransaction.h
  sdk/main/src/AccountBalanceQuery.cc
  sdk/main/src/AccountCreateTransaction.cc
  sdk/main/src/TransactionReceiptQuery.cc
  sdk/main/src/TransactionRecordQuery.cc
  sdk/main/src/TransferTransaction.cc
  sdk/tests/AccountBalanceQueryTest.cc
  sdk/tests/AccountCreateTransactionTest.cc
  sdk/tests/TransactionReceiptQueryTest.cc
  sdk/tests/TransactionRecordQueryTest.cc
  sdk/tests/TransferTransactionTest.cc
Labels: Improvement

#220 Implement `AccountUpdateTransaction`
  sdk/examples/CMakeLists.txt
  sdk/examples/UpdateAccountPublicKeyExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/AccountCreateTransaction.h
  sdk/main/include/AccountUpdateTransaction.h
  sdk/main/include/Client.h
  sdk/main/include/Transaction.h
  sdk/main/include/TransferTransaction.h
  sdk/main/include/exceptions/IllegalStateException.h
  sdk/main/src/AccountCreateTransaction.cc
  sdk/main/src/AccountUpdateTransaction.cc
  sdk/main/src/Client.cc
  sdk/main/src/Executable.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/TransferTransaction.cc
  sdk/tests/AccountCreateTransactionTest.cc
  sdk/tests/AccountUpdateTransactionTest.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/TransactionTest.cc
  sdk/tests/TransferTransactionTest.cc
Labels: New Feature

#223 Complete implementation for NodeAddress (PR)
  sdk/main/include/impl/Endpoint.h
  sdk/main/include/impl/Node.h
  sdk/main/include/impl/NodeAddress.h
  sdk/main/src/impl/Endpoint.cc
  sdk/main/src/impl/Node.cc
  sdk/main/src/impl/NodeAddress.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/NodeAddressTest.cc
Labels: Blocker

#227 Switch `std::vector<unsigned char>` to `std::vector<std::byte>`
  sdk/main/include/Client.h
  sdk/main/include/ECDSAsecp256k1PrivateKey.h
  sdk/main/include/ECDSAsecp256k1PublicKey.h
  sdk/main/include/ED25519PrivateKey.h
  sdk/main/include/ED25519PublicKey.h
  sdk/main/include/EvmAddress.h
  sdk/main/include/Mnemonic.h
  sdk/main/include/MnemonicBIP39.h
  sdk/main/include/PrivateKey.h
  sdk/main/include/PublicKey.h
  sdk/main/include/Transaction.h
  sdk/main/include/impl/DerivationPathUtils.h
  sdk/main/include/impl/HederaCertificateVerifier.h
  sdk/main/include/impl/HexConverter.h
  sdk/main/include/impl/IPv4Address.h
  sdk/main/include/impl/NodeAddress.h
  sdk/main/include/impl/PrivateKeyImpl.h
  sdk/main/include/impl/Utilities.h
  sdk/main/include/impl/openssl_utils/BIGNUM.h
  sdk/main/include/impl/openssl_utils/OpenSSLUtils.h
  sdk/main/src/AccountCreateTransaction.cc
  sdk/main/src/AccountId.cc
  sdk/main/src/Client.cc
  sdk/main/src/ECDSAsecp256k1PrivateKey.cc
  sdk/main/src/ECDSAsecp256k1PublicKey.cc
  sdk/main/src/ED25519PrivateKey.cc
  sdk/main/src/ED25519PublicKey.cc
  sdk/main/src/EvmAddress.cc
  sdk/main/src/Mnemonic.cc
  sdk/main/src/MnemonicBIP39.cc
  sdk/main/src/PrivateKey.cc
  sdk/main/src/PublicKey.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/TransactionRecord.cc
  sdk/main/src/impl/DerivationPathUtils.cc
  sdk/main/src/impl/HederaCertificateVerifier.cc
  sdk/main/src/impl/HexConverter.cc
  sdk/main/src/impl/IPv4Address.cc
  sdk/main/src/impl/NodeAddress.cc
  sdk/main/src/impl/OpenSSLUtils.cc
  sdk/main/src/impl/Utilities.cc
  sdk/tests/AccountCreateTransactionTest.cc
  sdk/tests/AccountIdTest.cc
  sdk/tests/ClientTest.cc
  sdk/tests/ECDSAsecp256k1PrivateKeyTest.cc
  sdk/tests/ECDSAsecp256k1PublicKeyTest.cc
  sdk/tests/ED25519PrivateKeyTest.cc
  sdk/tests/ED25519PublicKeyTest.cc
  sdk/tests/EvmAddressTest.cc
  sdk/tests/NodeAddressTest.cc
  sdk/tests/TransactionRecordTest.cc
  sdk/tests/TransactionTest.cc
  sdk/tests/vectors/RFC8032TestVectors.cc
Labels: Improvement

#233 Implement `AccountDeleteTransaction`
  sdk/examples/CMakeLists.txt
  sdk/examples/DeleteAccountExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/AccountDeleteTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/AccountDeleteTransaction.cc
  sdk/main/src/Executable.cc
  sdk/main/src/Transaction.cc
  sdk/tests/AccountDeleteTransactionTest.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/TransactionTest.cc
Labels: New Feature

#238 Add `Transaction::fromBytes()` tests for `AccountUpdateTransaction` and `AccountDeleteTransaction`
  sdk/tests/TransactionTest.cc
Labels: Escape

#242 Implement `AccountAllowanceApproveTransaction`
  sdk/examples/AccountAllowanceExample.cc
  sdk/examples/CMakeLists.txt
  sdk/examples/DeleteAccountExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/AccountAllowanceApproveTransaction.h
  sdk/main/include/AccountAllowanceDeleteTransaction.h
  sdk/main/include/HbarAllowance.h
  sdk/main/include/NftAllowance.h
  sdk/main/include/TokenAllowance.h
  sdk/main/include/TokenNftAllowance.h
  sdk/main/include/Transaction.h
  sdk/main/src/AccountAllowanceApproveTransaction.cc
  sdk/main/src/AccountAllowanceDeleteTransaction.cc
  sdk/main/src/Executable.cc
  sdk/main/src/HbarAllowance.cc
  sdk/main/src/TokenAllowance.cc
  sdk/main/src/TokenNftAllowance.cc
  sdk/main/src/Transaction.cc
  sdk/tests/AccountAllowanceApproveTransactionTest.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/HbarAllowanceTest.cc
  sdk/tests/HbarTransferTest.cc
  sdk/tests/TokenAllowanceTest.cc
  sdk/tests/TokenNftAllowanceTest.cc
  sdk/tests/TransactionTest.cc
Labels: New Feature

#244 Implement `AccountAllowanceDeleteTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/AccountAllowanceDeleteTransaction.h
  sdk/main/include/TokenNftRemoveAllowance.h
  sdk/main/include/Transaction.h
  sdk/main/src/AccountAllowanceApproveTransaction.cc
  sdk/main/src/AccountAllowanceDeleteTransaction.cc
  sdk/main/src/Executable.cc
  sdk/main/src/TokenNftRemoveAllowance.cc
  sdk/main/src/Transaction.cc
  sdk/tests/AccountAllowanceDeleteTransactionTest.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/TokenNftRemoveAllowanceTest.cc
  sdk/tests/TransactionTest.cc
Labels: New Feature

#246 Implement `AccountInfoQuery`
  sdk/examples/CMakeLists.txt
  sdk/examples/StakingExample.cc
  sdk/examples/UpdateAccountPublicKeyExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/AccountInfo.h
  sdk/main/include/AccountInfoQuery.h
  sdk/main/include/LedgerId.h
  sdk/main/include/StakingInfo.h
  sdk/main/include/TransferTransaction.h
  sdk/main/src/AccountInfo.cc
  sdk/main/src/AccountInfoQuery.cc
  sdk/main/src/Executable.cc
  sdk/main/src/LedgerId.cc
  sdk/main/src/StakingInfo.cc
  sdk/tests/AccountInfoQueryTest.cc
  sdk/tests/AccountInfoTest.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/LedgerIdTest.cc
  sdk/tests/StakingInfoTest.cc
Labels: New Feature

#248 Implement `ContractByteCodeQuery`
  sdk/main/CMakeLists.txt
  sdk/main/include/ContractByteCodeQuery.h
  sdk/main/include/TransferTransaction.h
  sdk/main/include/impl/Node.h
  sdk/main/src/ContractByteCodeQuery.cc
  sdk/main/src/Executable.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/ContractByteCodeQueryTest.cc
Labels: New Feature

#251 Implement `ContractCreateTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/ContractCreateTransaction.h
  sdk/main/include/FileId.h
  sdk/main/include/Transaction.h
  sdk/main/src/ContractCreateTransaction.cc
  sdk/main/src/Executable.cc
  sdk/main/src/FileId.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/CMakeLists.txt
  sdk/tests/ContractCreateTransactionTest.cc
  sdk/tests/FileIdTest.cc
  sdk/tests/TransactionTest.cc
Labels: New Feature
