Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2023-05, with the labels that each got.

#288 Integration tests fail to build on Windows
  sdk/tests/integration/AccountBalanceQueryIntegrationTest.cc
  sdk/tests/integration/AccountCreateTransactionIntegrationTest.cc
  sdk/tests/integration/JSONIntegrationTest.cc
  sdk/tests/integration/TransactionReceiptQueryIntegrationTest.cc
  sdk/tests/integration/TransactionRecordQueryIntegrationTest.cc
  sdk/tests/integration/TransferTransactionIntegrationTest.cc
Labels: Bug

#289 Add integration tests for Contract service APIs
  sdk/main/include/ContractCreateTransaction.h
  sdk/main/src/ContractCreateTransaction.cc
  sdk/tests/integration/AccountBalanceQueryIntegrationTest.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/ContractBytecodeQueryIntegrationTests.cc
  sdk/tests/integration/ContractCallQueryIntegrationTests.cc
  sdk/tests/integration/ContractCreateTransactionIntegrationTests.cc
  sdk/tests/integration/ContractDeleteTransactionIntegrationTests.cc
  sdk/tests/unit/ContractCreateTransactionTest.cc
  sdk/tests/unit/ContractDeleteTransactionTest.cc
Labels: Improvement

#291 Implement `FileDeleteTransaction`
  sdk/examples/CMakeLists.txt
  sdk/examples/DeleteFileExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/FileCreateTransaction.h
  sdk/main/include/FileDeleteTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/FileDeleteTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/ContractBytecodeQueryIntegrationTests.cc
  sdk/tests/integration/ContractCallQueryIntegrationTests.cc
  sdk/tests/integration/ContractCreateTransactionIntegrationTests.cc
  sdk/tests/integration/FileDeleteTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/FileDeleteTransactionTest.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#296 Implement `ContractUpdateTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/ContractUpdateTransaction.h
  sdk/main/include/Transaction.h
  sdk/main/src/ContractUpdateTransaction.cc
  sdk/main/src/Executable.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/ContractUpdateTransactionIntegrationTests.cc
  sdk/tests/unit/AccountUpdateTransactionTest.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/ContractUpdateTransactionTest.cc
  sdk/tests/unit/TransactionTest.cc
Labels: New Feature

#307 Add integration tests for `FileCreateTransaction`
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/FileCreateTransactionIntegrationTests.cc
Labels: Improvement

#309 Add `TODO` processing in integration tests
  sdk/tests/integration/ContractUpdateTransactionIntegrationTests.cc
Labels: Improvement

#319 `RLPValue` library throws when a value is empty
  sdk/main/CMakeLists.txt
  sdk/main/include/impl/RLPItem.h
  sdk/main/src/EthereumTransactionData.cc
  sdk/main/src/EthereumTransactionDataEip1559.cc
  sdk/main/src/EthereumTransactionDataLegacy.cc
  sdk/main/src/impl/RLPItem.cc
Labels: Bug

#321 Implement `FileUpdateTransaction`
  sdk/main/CMakeLists.txt
  sdk/main/include/FileUpdateTransaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/FileUpdateTransaction.cc
  sdk/main/src/Transaction.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/FileUpdateTransactionIntegrationTests.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/FileUpdateTransactionTest.cc
Labels: New Feature

#323 Implement `FileContentsQuery`
  sdk/examples/CMakeLists.txt
  sdk/examples/GetFileContentsExample.cc
  sdk/main/CMakeLists.txt
  sdk/main/include/FileContentsQuery.h
  sdk/main/include/TransferTransaction.h
  sdk/main/src/Executable.cc
  sdk/main/src/FileContentsQuery.cc
  sdk/main/src/Query.cc
  sdk/main/src/impl/Node.cc
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/FileContentsQueryIntegrationTest.cc
  sdk/tests/unit/CMakeLists.txt
  sdk/tests/unit/FileContentsQueryTest.cc
Labels: New Feature

#325 Attempting to work with `std::vector<const Key*>` was causing crashing.
  sdk/main/include/FileCreateTransaction.h
  sdk/main/include/FileUpdateTransaction.h
  sdk/main/include/KeyList.h
  sdk/main/src/FileCreateTransaction.cc
  sdk/main/src/FileUpdateTransaction.cc
  sdk/main/src/KeyList.cc
  sdk/tests/unit/FileCreateTransactionTest.cc
  sdk/tests/unit/FileUpdateTransactionTest.cc
Labels: Bug

#297 Better coverage in the integration tests (PR)
  sdk/main/include/TransactionResponse.h
  sdk/tests/integration/CMakeLists.txt
  sdk/tests/integration/TransactionReceiptIntegrationTest.cc
  sdk/tests/integration/TransactionReceiptQueryIntegrationTest.cc
  sdk/tests/integration/TransactionRecordIntegrationTest.cc
  sdk/tests/integration/TransactionRecordQueryIntegrationTest.cc
Labels: Improvement
