Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2024-11, with the labels that each got.

#793 feat(tokenCreateTransaction): Implement JSON-RPC endpoint for `TokenCreateTransaction`
  src/sdk/main/include/CustomFractionalFee.h
  src/sdk/main/include/CustomRoyaltyFee.h
  src/sdk/main/include/FeeAssessmentMethod.h
  src/sdk/main/include/impl/EntityIdHelper.h
  src/sdk/main/src/CustomFractionalFee.cc
  src/sdk/main/src/CustomRoyaltyFee.cc
  src/sdk/main/src/PublicKey.cc
  src/sdk/main/src/impl/EntityIdHelper.cc
  src/sdk/tests/unit/CustomFractionalFeeUnitTests.cc
  src/sdk/tests/unit/CustomRoyaltyFeeUnitTests.cc
  src/sdk/tests/unit/FeeAssessmentMethodUnitTests.cc
  src/tck/CMakeLists.txt
  src/tck/include/token/CustomFeeSerializer.h
  src/tck/include/token/TokenService.h
  src/tck/include/token/params/CreateTokenParams.h
  src/tck/src/TckServer.cc
  src/tck/src/key/KeyService.cc
  src/tck/src/main.cc
  src/tck/src/sdk/SdkClient.cc
  src/tck/src/token/TokenService.cc
Labels: New Feature

#805 feat: add `Client::forMirrorNetwork()` to allow consensus node network initialization with a mirror node address book
  src/sdk/examples/CMakeLists.txt
  src/sdk/examples/InitializeClientWithMirrorNodeAddressBookExample.cc
  src/sdk/main/include/Client.h
  src/sdk/main/src/Client.cc
Labels: New Feature

#819 feat: Add network freeze
  src/sdk/tests/integration/NodeCreateTransactionIntegrationTests.cc
Labels: Improvement

#824 feat: Add optional Tests/TCK builds
  .github/workflows/zxc-build-library.yaml
  README.md
  src/CMakeLists.txt
  src/sdk/CMakeLists.txt
Labels: Feature Enhancement

#790 feat(tokenDeleteTransaction): Implement JSON-RPC endpoint for `TokenDeleteTransaction`
  src/sdk/CMakeLists.txt
  src/sdk/examples/ConstructClientExample.cc
  src/sdk/examples/ContractHelper.h
  src/sdk/main/include/FeeAssessmentMethod.h
  src/sdk/main/include/Transaction.h
  src/sdk/main/include/impl/MirrorNodeRouter.h
  src/sdk/main/src/FeeDataType.cc
  src/sdk/main/src/FreezeType.cc
  src/sdk/main/src/RequestType.cc
  src/sdk/main/src/Status.cc
  src/sdk/main/src/TokenKeyValidation.cc
  src/sdk/main/src/TokenSupplyType.cc
  src/sdk/main/src/TokenType.cc
  src/sdk/main/src/impl/ASN1ECPublicKey.cc
  src/sdk/main/src/impl/EntityIdHelper.cc
  src/sdk/tests/unit/ContractLogInfoUnitTests.cc
  src/sdk/tests/unit/ECDSAsecp256k1PrivateKeyUnitTests.cc
  src/sdk/tests/unit/ECDSAsecp256k1PublicKeyUnitTests.cc
  src/sdk/tests/unit/ED25519PrivateKeyUnitTests.cc
  src/sdk/tests/unit/ED25519PublicKeyUnitTests.cc
  src/sdk/tests/unit/NetworkUnitTests.cc
  src/sdk/tests/unit/TokenMintTransactionUnitTests.cc
  src/tck/include/token/CustomFeeSerializer.h
  src/tck/include/token/TokenService.h
  src/tck/include/token/params/DeleteTokenParams.h
  src/tck/src/TckServer.cc
  src/tck/src/account/AccountService.cc
  src/tck/src/key/KeyService.cc
  src/tck/src/main.cc
  src/tck/src/sdk/SdkClient.cc
  src/tck/src/token/TokenService.cc
Labels: New Feature

#815 feat(tokenUpdateTransaction): Implement JSON-RPC method endpoint for `TokenUpdateTransaction`
  src/sdk/main/include/Status.h
  src/sdk/main/src/ContractFunctionParameters.cc
  src/sdk/main/src/Status.cc
  src/tck/include/token/TokenService.h
  src/tck/include/token/params/UpdateTokenParams.h
  src/tck/src/TckServer.cc
  src/tck/src/main.cc
  src/tck/src/token/TokenService.cc
Labels: New Feature

#843 fix: Windows build
  src/sdk/main/include/Status.h
  src/tck/include/account/AccountService.h
  src/tck/include/account/params/CreateAccountParams.h
  src/tck/include/account/params/UpdateAccountParams.h
  src/tck/include/key/KeyService.h
  src/tck/include/sdk/SdkClient.h
  src/tck/src/TckServer.cc
Labels: Bug
