Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2024-08, with the labels that each got.

#748 feat(accountDeleteTransaction): Implement JSON-RPC endpoint for `AccountDeleteTransaction`
  src/tck/include/SdkClient.h
  src/tck/src/SdkClient.cc
  src/tck/src/main.cc
Labels: Feature Enhancement

#756 fix: don't fill out `accountIdToUpdate` if no account ID was provided
  src/sdk/main/src/AccountUpdateTransaction.cc
  src/sdk/tests/integration/AccountUpdateTransactionIntegrationTests.cc
Labels: Bug

#754 feat(HIP-869): Added DAB Node operations
  src/sdk/main/CMakeLists.txt
  src/sdk/main/include/Endpoint.h
  src/sdk/main/include/NodeCreateTransaction.h
  src/sdk/main/include/NodeDeleteTransaction.h
  src/sdk/main/include/NodeUpdateTransaction.h
  src/sdk/main/include/TransactionReceipt.h
  src/sdk/main/include/TransactionType.h
  src/sdk/main/include/WrappedTransaction.h
  src/sdk/main/src/Endpoint.cc
  src/sdk/main/src/Executable.cc
  src/sdk/main/src/NodeCreateTransaction.cc
  src/sdk/main/src/NodeDeleteTransaction.cc
  src/sdk/main/src/NodeUpdateTransaction.cc
  src/sdk/main/src/Transaction.cc
  src/sdk/main/src/TransactionReceipt.cc
  src/sdk/main/src/WrappedTransaction.cc
  src/sdk/tests/unit/CMakeLists.txt
  src/sdk/tests/unit/NodeCreateTransactionUnitTests.cc
  src/sdk/tests/unit/NodeDeleteTransactionUnitTests.cc
  src/sdk/tests/unit/NodeUpdateTransactionUnitTests.cc
  src/sdk/tests/unit/TokenRejectTransactionUnitTests.cc
Labels: New Feature
