Repository hiero-ledger/hiero-sdk-cpp, pull requests merged in 2024-10, with the labels that each got.

#795 fix: get rid of `curl` and replace its processing with `cpp-httplib`
  CMakeLists.txt
  src/sdk/main/CMakeLists.txt
  src/sdk/main/include/exceptions/CURLException.h
  src/sdk/main/include/impl/HttpClient.h
  src/sdk/main/src/AccountId.cc
  src/sdk/main/src/impl/HttpClient.cc
  src/sdk/main/src/impl/MirrorNodeGateway.cc
  src/sdk/tests/integration/CMakeLists.txt
  src/sdk/tests/integration/HttpClientIntegrationTests.cc
  vcpkg.json
Labels: dependencies

#787 feat: Added Integration Test for NodeCreateTransaction and FQDN support
  HederaApi.cmake
  src/sdk/main/include/IPv4Address.h
  src/sdk/main/include/Status.h
  src/sdk/main/include/impl/Node.h
  src/sdk/main/src/Endpoint.cc
  src/sdk/main/src/IPv4Address.cc
  src/sdk/main/src/Status.cc
  src/sdk/main/src/impl/Node.cc
  src/sdk/tests/integration/CMakeLists.txt
  src/sdk/tests/integration/NodeCreateTransactionIntegrationTests.cc
Labels: Improvement

#808 chore: Update runs-on stanza to use the appropriate latitude label
  .github/workflows/zxc-build-library.yaml
Labels: P0
